### ISSUE TITLE
Constructor returned NULL

### ISSUE THREAD

**Issue by jeanas** [dialect-app/dialect#334]
After changing the translator service to LibreTranslate, I got a system crash report, though the app didn't close:

```python
libretrans.py:83:__init__:TypeError: constructor returned NULL

Traceback (most recent call last):
  File "/usr/share/dialect/search_provider", line 208, in _on_settings_changed
    self.translator = self._get_translator()
                      ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/share/dialect/search_provider", line 193, in _get_translator
    translator = TRANSLATORS[backend](
                 ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/share/dialect/dialect/translators/libretrans.py", line 83, in __init__
    lang_message = Soup.Message.new('GET', self.lang_url)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: constructor returned NULL
```

This is with Dialect 2.1.1 installed from the Fedora 38 repos.

**Comment by mufeedali** [comment]
Have you encountered this on newer versions of the app?

**Comment by jeanas** [comment]
I just tried it again and it worked without issues. Closing.
