### ISSUE TITLE
Broken search provider with v2.4.0 flatpak

### ISSUE THREAD

**Issue by holterdipolter** [dialect-app/dialect#390]
Hi,
unfortunately the gnome search provider for the new 2.4.0 flatpak version seems to be broken. Journalctl does show this error:
```
Received error from D-Bus search provider app.drey.Dialect.desktop: Gio.DBusError: GDBus.Error:org.freedesktop.DBus.Error.NameHasNoOwner: Could not activate remote peer 'app.drey.Dialect.SearchProvider': unit failed
```
If I downgrade to 2.3.0, everything works fine again.

System: Gnome 46, Arch Linux

**Comment by thatAkiraFox** [comment]
I'm facing the same issue on Fedora Workstation 40 using Dialect v2.4.1.

`journalctl` shows this:
```
Jun 21 13:28:59 dumbFoxFedora flatpak[30703]: /app/share/dialect/dialect/providers/settings.py:7: PyGIWarning: Secret was imported without specifying a version first. Use gi.require_version('Secret', '1') before import to ensure that the right version gets loaded.
Jun 21 13:28:59 dumbFoxFedora flatpak[30703]:   from gi.repository import Gio, GLib, Secret
Jun 21 13:28:59 dumbFoxFedora flatpak[30702]: 2024-06-21T11:28:59.561848Z DEBUG oo7::portal::secret: Retrieve service key using org.freedesktop.portal.Secrets
Jun 21 13:28:59 dumbFoxFedora flatpak[30702]: 2024-06-21T11:28:59.561946Z DEBUG oo7::portal::secret: Creating a '/org/freedesktop/portal/desktop/request/1_377/oo7_bhPDlkh7nx' proxy and listening for a response
Jun 21 13:28:59 dumbFoxFedora flatpak[30702]: 2024-06-21T11:28:59.567019Z DEBUG oo7::portal::secret: Secret received from the portal successfully
Jun 21 13:28:59 dumbFoxFedora flatpak[30702]: 2024-06-21T11:28:59.567057Z DEBUG oo7::portal: Trying to load keyring file at "/home/akira/.var/app/com.belmoussaoui.Authenticator/data/keyrings/default.keyring"
Jun 21 13:28:59 dumbFoxFedora flatpak[30702]: 2024-06-21T11:28:59.567359Z DEBUG oo7::portal: Keyring file found, loading it content
Jun 21 13:28:59 dumbFoxFedora flatpak[30703]: /app/share/dialect/dialect/settings.py:6: PyGIWarning: Gtk was imported without specifying a version first. Use gi.require_version('Gtk', '4.0') before import to ensure that the right version gets loaded.
Jun 21 13:28:59 dumbFoxFedora flatpak[30703]:   from gi.repository import Gio, GLib, GObject, Gtk
Jun 21 13:28:59 dumbFoxFedora flatpak[30703]: Traceback (most recent call last):
Jun 21 13:28:59 dumbFoxFedora flatpak[30703]:   File "/app/share/dialect/search_provider", line 293, in <module>
Jun 21 13:28:59 dumbFoxFedora flatpak[30703]:     app = TranslateServiceApplication()
Jun 21 13:28:59 dumbFoxFedora flatpak[30703]:           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Jun 21 13:28:59 dumbFoxFedora flatpak[30703]:   File "/app/share/dialect/search_provider", line 246, in __init__
Jun 21 13:28:59 dumbFoxFedora flatpak[30703]:     self.service_object = TranslateService()
Jun 21 13:28:59 dumbFoxFedora flatpak[30703]:                           ^^^^^^^^^^^^^^^^^^
Jun 21 13:28:59 dumbFoxFedora flatpak[30703]:   File "/app/share/dialect/search_provider", line 81, in __init__
Jun 21 13:28:59 dumbFoxFedora flatpak[30703]:     self._load_translator()
Jun 21 13:28:59 dumbFoxFedora flatpak[30703]:   File "/app/share/dialect/search_provider", line 220, in _load_translator
Jun 21 13:28:59 dumbFoxFedora flatpak[30703]:     self.translator.init_trans(on_done, on_fail)
Jun 21 13:28:59 dumbFoxFedora flatpak[30703]:   File "/app/share/dialect/dialect/providers/modules/google.py", line 369, in init_trans
Jun 21 13:28:59 dumbFoxFedora flatpak[30703]:     on_done()
Jun 21 13:28:59 dumbFoxFedora flatpak[30703]:   File "/app/share/dialect/search_provider", line 206, in on_done
Jun 21 13:28:59 dumbFoxFedora flatpak[30703]:     self.dest_language = self.translator.dest_langs[0]
Jun 21 13:28:59 dumbFoxFedora flatpak[30703]:                          ^^^^^^^^^^^^^^^^^^^^^^^^^^
Jun 21 13:28:59 dumbFoxFedora flatpak[30703]: AttributeError: 'Provider' object has no attribute 'dest_langs'. Did you mean: 'dest_langs_for'?

```

**Comment by GerryT11** [comment]
I can reproduce this error with Dialect 2.4.1 flatpak (on Ubuntu 24.04)
