### ISSUE TITLE
[Bug] Doesn't start properly

### ISSUE THREAD

**Issue by kands-code** [dialect-app/dialect#395]
I recently updated Flatpak's Gnome Runtime, and when I started Dialect again, I got the following warnning and didn't work properly:

```default
> flatpak run app.drey.Dialect 

(process:2): Gtk-WARNING **: 16:57:37.694: Locale not supported by C library.
	Using the fallback 'C' locale.
Traceback (most recent call last):
  File "/app/share/dialect/dialect/widgets/textview.py", line 35, in __init__
    self._font_size = Settings.get().system_font_size
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/share/dialect/dialect/settings.py", line 125, in system_font_size
    return int(gtk_font_name_parts[1])
               ~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range
Traceback (most recent call last):
  File "/app/share/dialect/dialect/widgets/textview.py", line 35, in __init__
    self._font_size = Settings.get().system_font_size
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/share/dialect/dialect/settings.py", line 125, in system_font_size
    return int(gtk_font_name_parts[1])
               ~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range
```

![image](https://github.com/user-attachments/assets/21be2678-7e57-4b06-8ebc-d63a1e1a12f7)

I don't know how to look further but I'll do my best to help if needed.

**Comment by rafaelmardojai** [comment]
Should be fixed by 2.4.2
